### ISSUE TITLE
Breaks usage of ASDF:MONOLITHIC-CONCATENATE-SOURCE-OP

### ISSUE THREAD

**Issue by spwhitton** [e-user/cl-heredoc#2]
Hello,

Thanks for CL-HEREDOC!

I noticed that the .asd file contains the definition of the cl-heredoc-system package, which means that you can't successfully load package.lisp without first loading the cl-heredoc.asd.  As I understand this is not how ASDF systems are meant to work -- it should be possible to load the packages without loading ASDF or the system definition.  This is how ASDF:MONOLITHIC-CONCATENATE-SOURCE-OP works -- it prepares a single .lisp file with all your dependencies to load into Lisp, but it doesn't include the .asd files, because if all the dependencies are known to be available then they are not needed.

Could the cl-heredoc-system package be defined in package.lisp, or just dropped?

Thanks.

**Comment by outergod** [comment]
Hi @spwhitton,

Thanks for your bug report. It's really cool to see someone use something I wrote so long ago. To be perfectly honest, I don't have a working CL implementation on my system right now, and I'm sure I used whatever ASDF setup was considered to be conventional at the time when I wrote CL-HEREDOC. If you could provide a PR with the change to fix the issue, I'll happily merge it trusting you to do the right thing. Do you think you could do that? I'm not sure I have the patience to get back into CL development at this time.

Cheers

**Comment by spwhitton** [comment]
Thanks for looking!  CL-HEREDOC suits [my current project](https://spwhitton.name/doc/consfigurator/introduction.html) very well.  I prepared a patch and tried running the tests, and tried the thing which was previously broken in my project.  Everything seems okay so far as I can tell.
